source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example' do
  pod "CYLMWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Tests' do
  pod "CYLMWPhotoBrowser", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
